config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  ActiveAdmin.routes(self)

  resources :recommendations
  resources :users
  resources :notifications
  resources :profiles
  resources :rooms do
    resources :messages
  end
  # root to: 'rooms#index'
  resources :samples do
    collection do
      get 'generate_pdf', format: :pdf
    end
  end
  resources :tamplates, only: [] do
    collection do
      get 'upload_csv'  
      post 'import_csv'  
    end
  end
  put '/samples', to: 'samples#update'
  get '/signin', to: 'sessions#new'
  post '/signin', to: 'sessions#create'
  delete '/signout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/example.rb
class Example < ApplicationRecord
	validate :age_given
	# before_save :age_given

	def age_given
		if self.age>=10
			p "ok"
		else
			errors.add(:age, "must greater than 10")
		end		
	end
end

app/models/invoice.rb
class Invoice < ApplicationRecord
	mount_uploader :attachment, PdfUploaderUploader
end

app/models/item.rb
class Item < ApplicationRecord
	has_many :user_item_interactions
end

app/models/message.rb
class Message < ApplicationRecord
  has_noticed_notifications

  belongs_to :user
  belongs_to :room

  before_create :confirm_participant 
  after_create_commit { broadcast_append_to self.room }
  # after_create_commit :send_notification
  after_create_commit :notify_user

  def confirm_participant
    if self.room.is_private
      is_participant = Participant.where(user_id: self.user.id, room_id: self.room.id).first
      throw :abort unless is_participant
    end
  end

  private

  def notify_user
    pa=Participant.where.not(user_id: user_id).where(room_id: room_id)

    pa.map(&:user).each do |user|
      MessageNotification.with(message: self).deliver_later(user)
    end 
  end
  # def send_notification
  #   recipient_users = room.users.where.not(id: user_id)
  #   recipient_users.each do |recipient|
  #     Notification.with(message: self).deliver(recipient)
  #   end
  # end
end

app/models/notification.rb
class Notification < ApplicationRecord
  include Noticed::Model
  belongs_to :recipient, polymorphic: true

  after_create_commit :broadcast_to_recipient

  # scope :user_notifications, ->(user) { where(recipient: user) }

  def broadcast_to_recipient
    broadcast_append_later_to(
      recipient,
      :notifications,
      target: 'notifications-list',
      partial: 'notifications/notification',
      locals: {
        notification: self
      }
    )
  end
end

app/models/participant.rb
class Participant < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  has_one_attached :profile_picture
end

app/models/room.rb
class Room < ApplicationRecord
	validates :room_name, uniqueness: true

	scope :public_rooms, -> { where(is_private: false) }

	after_create_commit { broadcast_if_public }

	has_many :messages

	def broadcast_if_public
	  broadcast_append_to "rooms" unless self.is_private
	end

	def self.create_private_room(users, room_name)
		byebug
	  single_room = Room.create(room_name: room_name, is_private: true)
	  users.each do |user|
	    Participant.create(user_id: user.id, room_id: single_room.id )
	  end
	  single_room
	end
end

app/models/sample.rb
class Sample < ApplicationRecord
	# before_save :set_name
	# include ActiveModel::Dirty
	# attr_accessor :fullname, :first_name, :last_name
	# define_attribute_methods :fullname
	enum status: [ :active, :inactive, :expired ]
has_paper_trail
	def set_name
		if self.fullname.present? 
			if self.fullname.split.count>1
				countword = self.fullname.split.count
				names = fullname.split(" ")
				self.first_name=names[0...countword-1].join(' ')
				self.last_name = names[countword-1]
			else	
				self.first_name = self.fullname.strip.capitalize
			end
		elsif self.first_name.present? || self.last_name.present?
			self.fullname = [self.first_name.strip.capitalize, self.last_name.strip.capitalize].join(' ')	
		end
	end

	def track_fullname
		
		if fullname_previously_changed?
			puts "Fullname is changed from #{fullname_previous_change.first} to #{fullname}"
		else
			puts "Fullname is not changed"	
		end	
	end
end

app/models/store.rb
class Store < ApplicationRecord
	# include ActiveModel::Dirty
	has_secure_password

	# attr_accessor :name

	# def initialize(name)
    # 	@name = name
  	# end
	# def track
	# 	if name_changed?
	# 		puts "from #{name_was} to #{name}"
	# 	else
	# 		puts "Not"	
	# 	end
	# end

	has_paper_trail
	# validate :names

	# def names
	# 	names.include?("")
	# end
end

app/models/tamplate.rb
class Tamplate < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
 	has_secure_password

 	validates :email, uniqueness: true, presence: true
 	validates :password, presence: true
	validates :name, uniqueness: true, presence: true

	scope :all_except, ->(user) { where.not(id: user) }

	after_create_commit { broadcast_append_to "users" }

	has_many :messages
	has_many :notifications, as: :recipient
	has_one :profile
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/samples_helper.rb
module SamplesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/csv/upload_csv.html.erb
<%= form_for :dump, url: {action: "import_csv"}, html: { multipart: true
} do |f| %>
<table>
  <tr>
    <td>
      <label for="dump_file"> Select a CSV File : </label>
    </td>
    <td><%= f.file_field :file %></td>
  </tr>
  <tr>
    <td><%= submit_tag 'Submit' %></td>
  </tr>
</table>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="/">Chat App</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <!-- <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li> -->

      <!-- <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li> -->
     <!--  <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li> -->
     <!--  <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li> -->
      <% if @current_user.present? %>
        <li class="nav-item dropdown">
          <!-- <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Notifications<#%= @current_user.notifications.count %>
          </a> -->
            <a class="nav-link dropdown-toggle" type="button" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Notifications<%= @current_user.notifications.count %>
            </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= turbo_frame_tag "notifications", src: notifications_path %>
          </div>
        </li>
        <!-- <li><#%= link_to 'Profile', edit_profile_path(id: current_user.id) %></li> -->
        <li><%= link_to 'Profile', new_profile_path %></li>
      <% end %>

    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

<script>
  document.addEventListener("DOMContentLoaded", function() {
    document.querySelectorAll('.dropdown-toggle').forEach(function(dropdownToggle) {
      dropdownToggle.addEventListener('click', function(event) {
        event.preventDefault(); 
        event.stopPropagation(); 
        var dropdownMenu = this.nextElementSibling;
        if (dropdownMenu.classList.contains('show')) {
          dropdownMenu.classList.remove('show');
        } else {
          dropdownMenu.classList.add('show');
        }
      });
    });

    document.addEventListener('click', function(event) {
      var dropdowns = document.querySelectorAll('.dropdown-menu');
      dropdowns.forEach(function(dropdown) {
        if (!dropdown.contains(event.target)) {
          dropdown.classList.remove('show');
        }
      });
    });
  });

</script>

app/views/layouts/_new_message_form.html.erb
<div class="form-group msg-form">
  <%= form_with(model: [@single_room ,@message], remote: true, class: "d-flex" ) do |f| %>
    <%= f.text_field :content, id: 'chat-text', class: "form-control msg-content", autocomplete: 'off' %>
    <%= f.submit data: { disable_with: false }, class: "btn btn-primary", onclick: "clearInput()" %>
  <% end %>
</div>

<script>
  function clearInput() {
    setTimeout(function() {
      document.getElementById("chat-text").value = ""
    }, 0);
  }
</script>

app/views/layouts/_new_room_form.html.erb
<%= form_with(model: @room, remote: true, class: "d-flex" ) do |f| %>
  <%= f.text_field :room_name, class: "form-control", autocomplete: "on" %>
  <%= f.submit data: { disable_with: false } %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Recommendation</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= javascript_importmap_tags %>

    <style>
      <%= ".msg-#{current_user&.id}" %> {
      background-color: #007bff !important;
      padding: 10px;
      }
      <%= ".cont-#{current_user&.id}" %> {
      display: flex;
      justify-content: flex-end
      }
    </style>
    <%= javascript_include_tag 'notifications' %>


  </head>

  <body>
    <%= render "layouts/navbar" %>
    <%= yield %>

  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

<% if current_user %>
	<%= link_to "Start Chatting...", rooms_path %>
	<!-- <#%= link_to "All messages", message_path, class: "text-blue-500" %> -->
	<%= button_to "Logout", signout_path,  :method => :delete %>
	<!-- <#%= turbo_frame_tag "notifications", src: notifications_path %> -->
<% else %>
	<%= link_to "Login", signin_path %>
	<%= link_to "Sign Up", new_user_path %>
<% end %>